Accrue interest over time
d-EURO/smartContracts pull request #102
Opened 2024-12-23 00:32 UTC by lapatric

2024-12-26 18:57 UTC, TaprootFreak approved these changes

2024-12-27 13:41 UTC, konstantinullrich requested changes

2024-12-27 13:41 UTC, konstantinullrich commented on test/ForceSaleTests.ts
> +      // expect(await dEURO.equity()).to.be.lessThan(equity);
Please revert and see if test is passing

2024-12-27 13:51 UTC, konstantinullrich approved these changes

2024-12-27 13:54 UTC, merged